package com.github.smirnovdm2107.config;

public enum ConfigTokenType {
    GRAMMAR, SEMICOLON, COLON,
    STRING, OR, REGEXP, MANY, SOME,
    OPTIONAL, LP, RP, RANGE, EOF,
    UPPER_CASE_IDENTIFIER, LOWER_CASE_IDENTIFIER, CODE_BLOCK,
    RETURNS, RB, LB, COMMA
}
